### ISSUE TITLE
UndefinedFunctionException in UrlEncryptor.php line 26:

### ISSUE THREAD

**Issue by alvinbunk** [NAYZO/NzoUrlEncryptorBundle#22]
I'm using the NzoUrlEncryptorBundle with a Symfony3 project, and I have the app/config/config.yml secret set. Then in my Controller I call this:

`$banIDSecure = $this->get('nzo_url_encryptor')->encrypt($banID);`

But when I load my Symfony page (for this route), it shows:

UndefinedFunctionException in UrlEncryptor.php line 26: Attempted to call function "mcrypt_module_open" from namespace "Nzo\UrlEncryptorBundle\UrlEncryptor".

When I check the file "vendor/nzo/url-encryptor-bundle/Nzo/UrlEncryptorBundle/UrlEncryptor/UrlEncryptor.php" on line 26, it shows this:
`$mod = mcrypt_module_open(MCRYPT_DES, '', MCRYPT_MODE_ECB, '');`

Which looks good.
I have Symfony3 and php70u-mcrypt installed.

Any suggestions?

**Comment by NAYZO** [comment]
IMHO your issue is related to your PHP / "mcrypt" extension installation and/or configuration.
Could you please make sure that "mcrypt" extension is enabled in your php.ini file.
And if you use Apache please make sure that the "mcrypt.so" extension is correctly loaded in your (/etc/php5/apache2/php.ini) and also in CLI (/etc/php5/cli/php.ini).

**Comment by alvinbunk** [comment]
I figured out the problem. I'm on CentOS. It's as simple as "service httpd restart". Restarted Apache.
